kind: ConfigMap
apiVersion: v1
metadata:
  name: singleinstance-qm-configmap
data:
  mq.ini: |
    Channels:
      MaxChannels=200
      MaxActiveChannels=100

  tls.mqsc: |
    DEFINE QLOCAL('ORDER') DEFPSIST(YES) REPLACE 
    
    DEFINE QLOCAL('ORDERLOG') REPLACE
    ALTER QLOCAL('ORDER') STRMQOS(BESTEF) STREAMQ('ORDERLOG')
    
    DEFINE CHANNEL(SICHL) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) REPLACE
    SET CHLAUTH(SICHL) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)
